name: todo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  google_api_availability: ^5.0.0
  shared_preferences: ^2.3.2
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  logger: ^2.4.0
  image_picker: ^1.1.2
  jiffy: ^6.3.1
  provider: ^6.1.2
  intl: ^0.19.0
  animated_splash_screen: ^1.3.0
  dio: ^5.0.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  pretty_dio_logger:
  dartz: ^0.10.1
  country_phone_validator: ^1.0.1
  country_code_picker: ^3.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  dotted_border: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/

